#!/usr/bin/env python3
"""
export_data_js.py
Reads updish.db and writes data.js for the map.
Run after any pipeline stage that changes business data.
"""

import sqlite3
import json
import time
import os

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "updish.db")
OUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data.js")

BENCHMARKS = [
    {"stat": "31–34%", "desc": "avg food cost ratio for BC independents", "source": "Restaurants Canada 2026"},
    {"stat": "~62%", "desc": "of new food licences survive 3+ years in Vancouver", "source": "BC Stats 2025"},
    {"stat": "$42k", "desc": "median annual revenue per seat, full-service", "source": "TouchBistro 2025"},
    {"stat": "3.4×", "desc": "Kitsilano café density vs city average", "source": "CoV Open Data"},
    {"stat": "~8%", "desc": "net margin for healthy independent café", "source": "Restaurants Canada"},
    {"stat": "28–32%", "desc": "target labour cost as % of revenue", "source": "TouchBistro 2025"},
]


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def get_pipeline_status(conn):
    """Get last run time for each pipeline stage."""
    stages = ["sync_licences", "merge_osm", "scrape_html"]
    status = {}
    for stage in stages:
        row = conn.execute("""
            SELECT finished_at, records_processed, records_changed, message
            FROM pipeline_log
            WHERE stage=? AND status='ok'
            ORDER BY finished_at DESC LIMIT 1
        """, (stage,)).fetchone()
        status[stage] = dict(row) if row else None
    return status


def main():
    conn = get_db()

    # Pull all active businesses with coordinates
    rows = conn.execute("""
        SELECT name, address, neighbourhood, type, licence_type,
               employees, lat, lng, website, website_status,
               html_fetched_at, licence_status
        FROM businesses
        WHERE lat IS NOT NULL AND lng IS NOT NULL
        AND licence_status = 'active'
        ORDER BY neighbourhood, name
    """).fetchall()

    businesses = []
    for r in rows:
        b = {
            "name": r["name"],
            "address": r["address"] or "",
            "neighbourhood": r["neighbourhood"] or "Vancouver",
            "type": r["type"] or "restaurant",
            "employees": r["employees"] or 0,
            "licence": r["licence_type"] or "",
            "status": r["licence_status"],
            "lat": r["lat"],
            "lng": r["lng"],
        }
        if r["website"]:
            b["website"] = r["website"]
            b["website_status"] = r["website_status"] or "unknown"
        businesses.append(b)

    # Pipeline status for the dashboard
    pipeline_status = get_pipeline_status(conn)

    # Stats
    total = len(businesses)
    with_web = sum(1 for b in businesses if b.get("website"))
    by_type = {}
    for b in businesses:
        by_type[b["type"]] = by_type.get(b["type"], 0) + 1

    meta = {
        "generated_at": time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime()),
        "total": total,
        "with_websites": with_web,
        "by_type": by_type,
        "pipeline": pipeline_status,
    }

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// UpDish — generated by export_data_js.py\n")
        f.write(f"// {meta['generated_at']} · {total} businesses · {with_web} websites\n\n")
        f.write("const BUSINESSES = ")
        f.write(json.dumps(businesses, indent=2, ensure_ascii=False))
        f.write(";\n\n")
        f.write("const BENCHMARKS = ")
        f.write(json.dumps(BENCHMARKS, indent=2))
        f.write(";\n\n")
        f.write("const META = ")
        f.write(json.dumps(meta, indent=2))
        f.write(";\n")

    print(f"Exported {total} businesses ({with_web} with websites) to data.js")
    print(f"Generated: {meta['generated_at']}")
    conn.close()


if __name__ == "__main__":
    main()
